language: php

php:
    - 5.5
    - 5.6
    - hhvm
    - nightly

before_script:
    - composer self-update
    - composer update

script: vendor/bin/phpunit -c . --coverage-text

notifications:
    email:
        - "andreasprega@gmail.com"
